# Generated by Django 3.2.5 on 2022-04-13 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_dislike_like'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dislike',
            old_name='comment',
            new_name='coment',
        ),
        migrations.RenameField(
            model_name='like',
            old_name='comment',
            new_name='coment',
        ),
    ]
